"""
african_names.py — Lexique de noms propres africains (Bénin + sous-région).

Utilisé par le Detector pour renforcer la détection des noms propres
qui ne sont pas connus du modèle spaCy fr_core_news_lg (entraîné sur
des corpus essentiellement européens).

Structure :
    FAMILY_NAMES  — Noms de famille courants au Bénin et en Afrique de l'Ouest
    GIVEN_NAMES   — Prénoms courants (mixtes)
    COMPOUND_KEYS — Premières syllabes/racines permettant de reconnaître un nom

Sources : données publiques, annuaires téléphoniques, littérature académique.
"""

# ---------------------------------------------------------------------------
# Noms de famille — Bénin, Togo, Côte d'Ivoire, Sénégal, Burkina, Cameroun
# ---------------------------------------------------------------------------

FAMILY_NAMES: frozenset[str] = frozenset({
    # Bénin (groupes Fon, Yoruba, Bariba, Dendi, Goun, Adja)
    "Ahossou", "Ahouansou", "Ahovi", "Ahowé",
    "Aïssi", "Aïzoun",
    "Akpaglo", "Akplogan", "Akpo",
    "Alafia",
    "Allagbe", "Allagbada",
    "Amoussa", "Amoussou",
    "Anago",
    "Aplogan",
    "Assogba", "Assou",
    "Atindéhou",
    "Attanasso",
    "Avocèvou",
    "Azonhiho",
    "Azonnaho",
    "Codjo",
    "Dah", "Dahoun",
    "Dangnivo",
    "Degla",
    "Déguénon",
    "Djohossou", "Djosse",
    "Domingo", "Domingos",
    "Dossou", "Dossouvi",
    "Dovonon",
    "Fassinou",
    "Favi",
    "Gangbe",
    "Gbaguidi", "Gbékon", "Gbènou", "Gbès",
    "Gnansounou",
    "Gnonhossou",
    "Hessou",
    "Houehanou",
    "Houessou", "Houéto",
    "Hounkpè", "Hounkpatin",
    "Houssou",
    "Idohou",
    "Kèkè", "Kérékou",
    "Kindé",
    "Koba",
    "Koffi",
    "Kouagou", "Kouassi",
    "Lougbégnon",
    "Maïga",
    "Medenou",
    "Migan",
    "Montcho",
    "Noudékindé",
    "Ogoubiyi", "Ogoundélé",
    "Olou",
    "Pèlèbè",
    "Sagbohan",
    "Sessou",
    "Sodji",
    "Sossou",
    "Soukpe", "Soukpèdé",
    "Soumah",
    "Soumano",
    "Soumanou",
    "Talon",
    "Tankpinou",
    "Tchabi", "Tchagninou",
    "Tchibozo",
    "Togbadja",
    "Tohouindji",
    "Totin",
    "Toviho",
    "Vigan",
    "Vodounon",
    "Yao",
    "Zannou", "Zinsou", "Zinzindohoué",
    "Zomahoun",

    # Togo
    "Agbessi", "Agbodjan",
    "Akakpo",
    "Amégnona",
    "Anani",
    "Attipou",
    "Folly",
    "Koudjo", "Kouma",
    "Laba",
    "Mensah",
    "Nyavor",
    "Tetteh", "Togbui",

    # Côte d'Ivoire
    "Bamba", "Banny",
    "Coulibaly",
    "Diabaté",
    "Diaby",
    "Drogba",
    "Gbagbo",
    "Gueï",
    "Koné",
    "Kouyaté",
    "Ouattara",
    "Touré",
    "Traoré",
    "Yapo",
    "Yapi",

    # Sénégal / Guinée
    "Baldé",
    "Barry",
    "Camara",
    "Condé",
    "Daffe",
    "Diallo",
    "Diop",
    "Faye",
    "Gaye",
    "Kane",
    "Keïta",
    "Konaté",
    "Mbaye", "Mboup",
    "Ndiaye",
    "Sall",
    "Samb",
    "Sarr",
    "Sow",
    "Sylla",
    "Tall",
    "Thiam",
    "Touré",

    # Burkina Faso / Mali
    "Compaoré",
    "Dakuyo",
    "Kaboré", "Kafando",
    "Ouédraogo",
    "Sankara",
    "Sawadogo",
    "Zongo",

    # Cameroun / Centrafrique
    "Biya",
    "Ekwalla",
    "Fouda",
    "Mbappe",
    "Mbida",
    "Ndoumbe",
    "Nkemdirim",
    "Omam",
    "Tchoumba",
})


# ---------------------------------------------------------------------------
# Prénoms — courants en Bénin et en Afrique de l'Ouest
# ---------------------------------------------------------------------------

GIVEN_NAMES: frozenset[str] = frozenset({
    # Masculins
    "Abiodun", "Adéchina", "Adéwale", "Adjaï",
    "Adjovi", "Agossou",
    "Ahomed", "Aimé",
    "Akpè", "Akuévi",
    "Alexis",
    "Aloïse",
    "Alphonse",
    "Ambroise",
    "Anselme",
    "Antoine",
    "Barnabé",
    "Barthélémy",
    "Benjamin",
    "Bertrand",
    "Bienvenu",
    "Bonaventure",
    "Casimir",
    "Célestin",
    "Christophe",
    "Clément",
    "Codjo",
    "Cosme",
    "Crépin",
    "Cyprien",
    "Dèdè",
    "Denis",
    "Dieu-Donné",
    "Edmond",
    "Edouard",
    "Emile",
    "Epiphane",
    "Ernest",
    "Etienne",
    "Eudoxie",
    "Euloge",
    "Eustache",
    "Félix",
    "Ferdinand",
    "Fidèle",
    "Firmin",
    "Florentin",
    "François",
    "Fulgence",
    "Gaston",
    "Germain",
    "Gilbert",
    "Gilles",
    "Grégoire",
    "Guillaume",
    "Guy",
    "Hervé",
    "Hilaire",
    "Honoré",
    "Hyppolite",
    "Ignace",
    "Irenée",
    "Jacques",
    "Jean",
    "Jean-Baptiste",
    "Jean-Christophe",
    "Jean-Pierre",
    "Jean-Yves",
    "Jérôme",
    "Joseph",
    "Jules",
    "Julien",
    "Justin",
    "Kofi", "Kokou",
    "Laurent",
    "Lazare",
    "Léon", "Léopold",
    "Luc",
    "Lucien",
    "Marcel",
    "Martin",
    "Mathieu",
    "Maxime",
    "Modeste",
    "Moïse",
    "Narcisse",
    "Nicolas",
    "Norbert",
    "Octave",
    "Olivier",
    "Pascal",
    "Patrice",
    "Paul",
    "Philippe",
    "Pierre",
    "Prosper",
    "Raphaël",
    "Régis",
    "René",
    "Richard",
    "Robert",
    "Rodrigue",
    "Roland",
    "Roméo",
    "Séraphin",
    "Séverin",
    "Simon",
    "Simplice",
    "Socrate",
    "Stanislas",
    "Sylvain",
    "Théodore",
    "Théophile",
    "Thomas",
    "Timothée",
    "Toussaint",
    "Victor",
    "Vincent",
    "Xavier",
    "Yves",

    # Féminins
    "Abimbola", "Adaobi",
    "Adélaïde",
    "Adjoa",
    "Afua",
    "Agnès",
    "Aïchatou",
    "Aïda",
    "Albertine",
    "Alice",
    "Alphonsine",
    "Angèle",
    "Antoinette",
    "Arielle",
    "Aure",
    "Béatrice",
    "Bernadette",
    "Blandine",
    "Carole",
    "Cécile",
    "Célestine",
    "Charlotte",
    "Christine",
    "Claire",
    "Claudine",
    "Colette",
    "Constance",
    "Danielle",
    "Edwige",
    "Élise",
    "Emilienne",
    "Euphrasie",
    "Fatoumata",
    "Félicité",
    "Flore",
    "Florence",
    "Françoise",
    "Geneviève",
    "Georgette",
    "Germaine",
    "Grâce",
    "Honorine",
    "Hortense",
    "Joséphine",
    "Judith",
    "Julie",
    "Juliette",
    "Justine",
    "Léonie",
    "Lucie",
    "Madeleine",
    "Marguerite",
    "Marie",
    "Marie-Claire",
    "Marie-Madeleine",
    "Marie-Thérèse",
    "Marthe",
    "Martine",
    "Michelle",
    "Monique",
    "Nathalie",
    "Nicole",
    "Odette",
    "Pauline",
    "Perpétue",
    "Philomène",
    "Régine",
    "Rosalie",
    "Rose",
    "Rosette",
    "Sandrine",
    "Simone",
    "Solange",
    "Sophie",
    "Stéphanie",
    "Thérèse",
    "Valentine",
    "Valérie",
    "Véronique",
    "Victoire",
    "Virginie",
    "Viviane",
    "Yvette",
    "Yvonne",
})


# ---------------------------------------------------------------------------
# Index rapide : toutes les entrées en minuscules pour comparaison case-insensitive
# ---------------------------------------------------------------------------

ALL_NAMES_LOWER: frozenset[str] = frozenset(
    name.lower() for name in (FAMILY_NAMES | GIVEN_NAMES)
)


def is_african_name(word: str) -> bool:
    """
    Retourne True si le mot figure dans le lexique de noms africains.
    La comparaison est insensible à la casse.
    """
    return word.strip().lower() in ALL_NAMES_LOWER
