"""Add archived_at to User

Revision ID: 4a37e2c0f312
Revises: 8527ce64c6fd
Create Date: 2026-05-23 12:10:09.714104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a37e2c0f312'
down_revision: Union[str, Sequence[str], None] = '8527ce64c6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'archived_at')
    # ### end Alembic commands ###
