"""add_document_category

Revision ID: 5ee87815ecbe
Revises: 5713d8ba7ef2
Create Date: 2026-04-24 11:42:53.416416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee87815ecbe'
down_revision: Union[str, Sequence[str], None] = '5713d8ba7ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'category')
    # ### end Alembic commands ###
