"""remove_user_role

Revision ID: 8527ce64c6fd
Revises: eff1856b6289
Create Date: 2026-05-21 17:15:38.225173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8527ce64c6fd'
down_revision: Union[str, Sequence[str], None] = 'eff1856b6289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # Supprimer l'enum user_role obsolète
    op.execute("DROP TYPE user_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Récréer l'enum user_role
    op.execute("CREATE TYPE user_role AS ENUM ('pmo', 'chef_projet', 'direction', 'consultant')")
    op.add_column('users', sa.Column('role', postgresql.ENUM('pmo', 'chef_projet', 'direction', 'consultant', name='user_role'), server_default=sa.text("'pmo'::user_role"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
