"""add_user_confirmation

Revision ID: 98291825fb2f
Revises: 574d31347edc
Create Date: 2026-06-01 12:23:14.451426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98291825fb2f'
down_revision: Union[str, Sequence[str], None] = '574d31347edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_confirmed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('confirmation_token', sa.String(length=255), nullable=True))
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'confirmation_token')
    op.drop_column('users', 'is_confirmed')
    # ### end Alembic commands ###
