"""add_anonymization_fields_to_documents

Revision ID: 9fe8bc2605ba
Revises: 162bfaf97d71
Create Date: 2026-04-24 15:09:49.174344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fe8bc2605ba'
down_revision: Union[str, Sequence[str], None] = '162bfaf97d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('documents', sa.Column(
        'is_anonymized',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false'),  # documents existants = non anonymisés
    ))
    op.add_column('documents', sa.Column(
        'anonymization_map',
        postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'anonymization_map')
    op.drop_column('documents', 'is_anonymized')
    # ### end Alembic commands ###
