"""remove unused doc_type column from documents

Revision ID: eff1856b6289
Revises: 9fe8bc2605ba
Create Date: 2026-04-27 13:02:08.709823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eff1856b6289'
down_revision: Union[str, Sequence[str], None] = '9fe8bc2605ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'doc_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_type', postgresql.ENUM('rapport', 'cr_reunion', 'planning', 'autre', name='doc_type'), server_default=sa.text("'autre'::doc_type"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
